In [32]:
import numpy as np
import tensorflow as tf

In [ ]:
a = tf.random_uniform([1])
b = tf.random_normal([1])
print("Session 1")
with tf.Session() as sess1:
    print(sess1.run(a))  # generates 'A1'
    print(sess1.run(a))  # generates 'A2'
    print(sess1.run(b))  # generates 'B1'
    print(sess1.run(b))  # generates 'B2'
print("Session 2")
with tf.Session() as sess2:
    print(sess2.run(a))  # generates 'A3'
    print(sess2.run(a))  # generates 'A4'
    print(sess2.run(b))  # generates 'B3'
    print(sess2.run(b))  # generates 'B4'

In [ ]:
a = tf.random_uniform([1], seed=1)
b = tf.random_normal([1])
# Repeatedly running this block with the same graph will generate the same
# sequence of values for 'a', but different sequences of values for 'b'.
print("Session 1")
with tf.Session() as sess1:
    print(sess1.run(a))  # generates 'A1'
    print(sess1.run(a))  # generates 'A2'
    print(sess1.run(b))  # generates 'B1'
    print(sess1.run(b))  # generates 'B2'
print("Session 2")
with tf.Session() as sess2:
    print(sess2.run(a))  # generates 'A1'
    print(sess2.run(a))  # generates 'A2'
    print(sess2.run(b))  # generates 'B3'
    print(sess2.run(b))  # generates 'B4'

In [ ]:
with tf.Session() as sess1:
    print(sess1.run(a))  # generates 'A1'
    print(sess1.run(a))  # generates 'A2'
    print(sess1.run(b))  # generates 'B1'
    print(sess1.run(b))  # generates 'B2'
print("Session 2")
with tf.Session() as sess2:
    print(sess2.run(a))  # generates 'A1'
    print(sess2.run(a))  # generates 'A2'
    print(sess2.run(b))  # generates 'B3'
    print(sess2.run(b))  # generates 'B4'

In [15]:
tf.set_random_seed(1234)
a = tf.random_uniform([1])
b = tf.random_uniform([1])
# Repeatedly running this block with the same graph will generate the same
# sequences of 'a' and 'b'.
print("Session 1")
with tf.Session() as sess1:
    print(sess1.run(a))  # generates 'A1'
    print(sess1.run(a))  # generates 'A2'
    print(sess1.run(b))  # generates 'B1'
    print(sess1.run(b))  # generates 'B2'
print("Session 2")
with tf.Session() as sess2:
    print(sess2.run(a))  # generates 'A1'
    print(sess2.run(a))  # generates 'A2'
    print(sess2.run(b))  # generates 'B1'
    print(sess2.run(b))  # generates 'B2'

Session 1
[ 0.72257137]
[ 0.35829496]
[ 0.58526564]
[ 0.96515763]
Session 2
[ 0.72257137]
[ 0.35829496]
[ 0.58526564]
[ 0.96515763]


In [31]:
tf.set_random_seed(1)
a = tf.random_uniform([1,2],seed=1)
b = tf.random_uniform([3,3],seed=1)
# Repeatedly running this block with the same graph will generate the same
# sequences of 'a' and 'b'.
print("Session 1")
with tf.Session() as sess1:
    print(sess1.run(a))  # generates 'A1'
    #print(sess1.run(a))  # generates 'A2'
    print(sess1.run(b))  # generates 'B1'
    #print(sess1.run(b))  # generates 'B2'
print("Session 2")
with tf.Session() as sess2:
    print(sess2.run(a))  # generates 'A1'
    #print(sess2.run(a))  # generates 'A2'
    print(sess2.run(b))  # generates 'B1'
    #print(sess2.run(b))  # generates 'B2'

Session 1
[[ 0.05554414  0.01869845]]
[[ 0.05554414  0.01869845  0.07080972]
 [ 0.27141213  0.65317714  0.58058167]
 [ 0.93273187  0.4293102   0.41135514]]
Session 2
[[ 0.05554414  0.01869845]]
[[ 0.05554414  0.01869845  0.07080972]
 [ 0.27141213  0.65317714  0.58058167]
 [ 0.93273187  0.4293102   0.41135514]]


In [33]:
np.random.seed(1)
print(np.random.rand(10))

[  4.17022005e-01   7.20324493e-01   1.14374817e-04   3.02332573e-01
   1.46755891e-01   9.23385948e-02   1.86260211e-01   3.45560727e-01
   3.96767474e-01   5.38816734e-01]


In [34]:
a = tf.random_uniform([10],seed=1)
with tf.Session() as sess1:
    print(sess1.run(a))  # generates 'A1'

[ 0.05554414  0.01869845  0.07080972  0.27141213  0.65317714  0.58058167
  0.93273187  0.4293102   0.41135514  0.44323444]
